apiVersion: apps/v1
kind: Deployment
metadata:
  name: trailer-streaming-rest-deployment
spec:
  selector:
    matchLabels:
      service: trailer-streaming-rest
  template:
    metadata:
      labels:
        service: trailer-streaming-rest
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "8050"
    spec:
      containers:
      - name: trailer-streaming-rest
        image: mariammartirosyan/trailer-streaming-service-rest:latest
        ports:
        - containerPort: 80
        # - containerPort: 8050
        env:
        - name: AccountServiceUrl
          value: http://account-service-rest:8081     
        - name: StatisticsServiceUrl
          value: http://statistics-service-rest:8083                               
        # resources:
        #   limits:
        #     cpu: "0.5"    
        #     memory: "500Mi"
        #   requests:
        #     memory: "300Mi"
        #     cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: trailer-streaming-rest
  labels:
    service: trailer-streaming-rest
  # annotations:
  #   beta.cloud.google.com/backend-config: '{"default": "trailer-streaming-rest-backendconfig"}'
spec:
  selector:
    service: trailer-streaming-rest
  ports:
    - protocol: TCP
      targetPort: 80 
      port: 8084 
      name: api-port
    # - name: metrics
    #   protocol: TCP
    #   port: 8050
    #   targetPort: 8050
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: trailer-streaming-rest-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: trailer-streaming-rest
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: trailer-streaming-rest-monitor
#   labels:
#     app: "trailer-streaming-rest"
#     release: prometheus
# spec:
#   selector:
#     matchLabels:
#       app: "trailer-streaming-rest"
#   endpoints:
#     - port: metrics
#       interval: 15s
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: trailer-streaming-rest-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /metrics
#             pathType: Prefix
#             backend:
#               service:
#                 name: trailer-streaming-rest
#                 port:
#                   number: 8050
          # - path: /ping
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: trailer-streaming-rest
          #       port:
          #         number: 80
# ---
# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: trailer-streaming-rest-backendconfig
# spec:
#   healthCheck:
#     requestPath: /ping
#     port: 8084
#     type: HTTP

