apiVersion: apps/v1
kind: Deployment
metadata:
  name: trailer-streaming-rest-deployment
spec:
  selector:
    matchLabels:
      service: trailer-streaming-rest
  template:
    metadata:
      labels:
        service: trailer-streaming-rest
    spec:
      containers:
      - name: trailer-streaming-rest
        image: mariammartirosyan/trailer-streaming-service-rest:latest
        ports:
        - containerPort: 80
        env:
        - name: AccountServiceUrl
          value: http://account-service-rest:8081     
        - name: StatisticsServiceUrl
          value: http://statistics-service-rest:8083                               
        # resources:
        #   limits:
        #     cpu: "2"    
        #     memory: "6200Mi"
        #   requests:
        #     memory: "5000Mi"
        #     cpu: "1.8"
---
apiVersion: v1
kind: Service
metadata:
  name: trailer-streaming-rest
  labels:
    service: trailer-streaming-rest
spec:
  selector:
    service: trailer-streaming-rest
  ports:
    - protocol: TCP
      targetPort: 80 
      port: 8084 
      name: api-port
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: trailer-streaming-rest-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: trailer-streaming-rest
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50


