apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-web-socket-deployment
spec:
  selector:
    matchLabels:
      service: account-service-web-socket
  template:
    metadata:
      labels:
        service: account-service-web-socket
    spec:
      containers:
      - name: account-service-web-socket
        image: mariammartirosyan/account-service-web-socket:latest
        ports:
        - containerPort: 80
        env:
        # - name: DefaultConnection 
        #   value: Server=trailer-streaming-db;Database=TrailerStreamingSystemDB;User ID=root;Password=pass;Port=3307
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: Platform
          value: GKE
        - name: Server
          value: account-db
        - name: Database
          value: AccountDB
        - name: UserID
          value: root
        - name: Password
          value: pass    
        - name: Port
          value: "3310"                           
        # resources:
        #   limits:
        #     cpu: "0.3"    
        #     memory: "200Mi"
        #   requests:
        #     memory: "100Mi"
        #     cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service-web-socket
  namespace: default
  labels:
    service: account-service-web-socket
spec:
  selector:
    service: account-service-web-socket
  ports:
    - protocol: TCP
      targetPort: 80 
      port: 8085  
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: account-service-web-socket-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: account-service-web-socket
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50