apiVersion: apps/v1
kind: Deployment
metadata:
  name: trailer-streaming-web-socket-deployment
spec:
  selector:
    matchLabels:
      service: trailer-streaming-web-socket
  template:
    metadata:
      labels:
        service: trailer-streaming-web-socket
    spec:
      containers:
      - name: trailer-streaming-web-socket
        image: mariammartirosyan/trailer-streaming-service-web-socket:latest
        ports:
        - containerPort: 80
        env:
        - name: AccountServiceUrl
          value: ws://account-service-web-socket:8085    
        - name: StatisticsServiceUrl
          value: ws://statistics-service-web-socket:8083                               
        # resources:
        #   limits:
        #     cpu: "0.5"    
        #     memory: "500Mi"
        #   requests:
        #     memory: "300Mi"
        #     cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: trailer-streaming-web-socket
  namespace: default
  labels:
    service: trailer-streaming-web-socket
spec:
  selector:
    service: trailer-streaming-web-socket
  ports:
    - protocol: TCP
      targetPort: 80 
      port: 8084 
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: trailer-streaming-web-socket-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: trailer-streaming-web-socket
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50